# Full documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go-licenses check .
    - task generate
builds:
  - goos:
      - darwin
    goarch:
      - amd64
    ldflags:
     - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=robin@technisys.com      
archives:
  - replacements:
      darwin: Darwin
      amd64: x86_64
dockers:
  - 
    image_templates:
      - "tecdigitalacr.azurecr.io/utils/fca-emu:{{ .Tag }}"
      - "tecdigitalacr.azurecr.io/utils/fca-emu:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--build-arg=BUILD_VERSION={{.Version}}"
    - "--build-arg=BUILD_COMMIT={{.Commit}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--build-arg=BUILD_BY=robin@technisys.com"

    extra_files:
      - server
      - api
      - generator
      - swagger-ui
      - ent
      - util
      - main.go
      - go.sum
      - go.mod
      - banner.txt

# publishers:
#   - name: docker-export
#     cmd: |
#       docker save -o dist/fca-emu_{{ .Version }}_Docker_x86_64.tar \
#         tecdigitalacr.azurecr.io/utils/fca-emu:v{{ .Version }} && \
#         gzip dist/fca-emu_{{ .Version }}_Docker_x86_64.tar

#   - name: code-statistics
#     cmd: |
#       OUTPUT=dist/source_stats-{{ .Version }}.txt \
#         echo "Lines of written code:" > $OUTPUT && \
#         gocloc ./generator ./ent/schema ./server/*service*.go ./util ./server/helpers.go >> $OUTPUT && \
#         echo >> $OUTPUT && \
#         echo "Total lines of code (incl. generated):" >> $OUTPUT && \
#         gocloc . >> $OUTPUT

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: robinhuiser
    name: fca-emu