# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - task generate
builds:
  - goos:
      - darwin
    goarch:
      - amd64
    ldflags:
     - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=robin@technisys.com      
archives:
  - replacements:
      darwin: Darwin
      amd64: x86_64
dockers:
  - 
    image_templates:
      - "docker.io/rdclda/fca-emu:{{ .Tag }}"
      - "docker.io/rdclda/fca-emu:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - server
      - api
      - generator
      - swagger-ui
      - ent
      - util
      - main.go
      - go.sum
      - go.mod
      - banner.txt

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: robinhuiser
    name: fca-emu