#
# Environment setup
@base_url = http://localhost:{{$dotenv MOCK_SERVER_LISTEN_PORT}}/cloud

#
# Test account ID
@account_url = v1/account
@account_id = d9b20312-6df1-4830-80fd-1df9bc387c28

### 

# Get account details
# @name account
GET {{base_url}}/{{account_url}}/{{account_id}}
Accept: application/json
