#
# Environment setup
@base_url = http://localhost:{{$dotenv MOCK_SERVER_LISTEN_PORT}}/cloud
@access_token = {{$dotenv MOCK_SERVER_SECRET}}

#
# Test account ID
@account_url = v1/account
@account_id = e4c5b5b7-3b55-4718-8631-869d4b11c7db

### 

# Get account details
# @name account
GET {{base_url}}/{{account_url}}/{{account_id}}
Accept: application/json
X-TOKEN: {{access_token}}
X-TRACE-ID: {{$guid}}
