version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fca
      POSTGRES_USER: emulator
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data/pgdata

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fca
      MYSQL_USER: emulator
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-volume:/var/lib/mysql
  
  fca-emu:
    image: tecdigitalacr.azurecr.io/utils/fca-emu
    restart: always
    environment:
      DB_VENDOR: postgres
      DB_HOST: postgres
      DB_DATABASE_NAME: fca
      DB_USER_NAME: emulator
      DB_USER_PASSWORD: secret
      FCA_SECRET: VXNlclNlc3Npb25Ub2tlbjoxMjM0MTIzNA==
      TEST_DATA_ACCOUNTS: 100
    ports:
      - 8080:8080  

volumes:
  postgres-volume:
  mysql-volume: