version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - finite-mock-db:/var/lib/mysql

  mock:
    build:
      context: .
      args:
        - mock_server_port=${MOCK_SERVER_PORT}
    environment:
      MYSQL_HOST: db:3306 
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - ${MOCK_SERVER_PORT}:${MOCK_SERVER_PORT}   

volumes:
  finite-mock-db: