version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - finite-mock-db:/var/lib/postgresql/data/pgdata

  mock:
    build:
      context: .
      args:
        - port=${MOCK_SERVER_LISTEN_PORT}
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER_NAME: ${POSTGRES_USER_NAME}
      POSTGRES_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
    ports:
      - ${MOCK_SERVER_LISTEN_PORT}:${MOCK_SERVER_LISTEN_PORT}  
    depends_on:
      - db 

volumes:
  finite-mock-db: