version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: finite
      POSTGRES_USER: emulator
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - fca-emu-postgres:/var/lib/postgresql/data/pgdata

  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: finite
  #     MYSQL_USER: emulator
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   volumes:
  #     - fca-emu-mysql:/var/lib/mysql
  
  fca-emu:
    build:
      context: .
    restart: always
    environment:
      DB_VENDOR: postgres
      DB_HOST: postgres
      DB_DATABASE_NAME: finite
      DB_USER_NAME: emulator
      DB_USER_PASSWORD: secret
      FCA_SECRET: VXNlclNlc3Npb25Ub2tlbjoxMjM0MTIzNA==
      TEST_DATA_ACCOUNTS: 100
    ports:
      - 8080:8080  

volumes:
  fca-emu-postgres:
  fca-emu-mysql: