version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: finite
      POSTGRES_USER: mock
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - finite-mock-postgres:/var/lib/postgresql/data/pgdata

  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: finite
  #     MYSQL_USER: mock
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   volumes:
  #     - finite-mock-mysql:/var/lib/mysql
  
  mock:
    build:
      context: .
    restart: always
    environment:
      DB_VENDOR: postgres
      DB_HOST: postgres
      DB_DATABASE_NAME: finite
      DB_USER_NAME: mock
      DB_USER_PASSWORD: secret
      MOCK_SERVER_SECRET: VXNlclNlc3Npb25Ub2tlbjoxMjM0MTIzNA==
      TEST_DATA_ACCOUNTS: 100
    ports:
      - 8080:8080  

volumes:
  finite-mock-postgres:
  finite-mock-mysql: