/*
 * Cloud API
 *
 * The public facing API through which connectors are exposed as a single abtract API
 *
 * API version: v1.5
 * Contact: support@trexis.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finite

import (
	"context"
	"errors"
	"net/http"
)

// StatementsApiService is a service that implents the logic for the StatementsApiServicer
// This service should implement the business logic for every endpoint for the StatementsApi API.
// Include any external packages or services that will be required by this service.
type StatementsApiService struct {
}

// NewStatementsApiService creates a default api service
func NewStatementsApiService() StatementsApiServicer {
	return &StatementsApiService{}
}

// GetAccountStatements - Return a list of statements for a given account
func (s *StatementsApiService) GetAccountStatements(ctx context.Context, accountId string, mask bool, enhance bool, xTRACEID string, xTOKEN string) (ImplResponse, error) {

	return Response(http.StatusNotImplemented, nil), errors.New("GetAccountStatements method not implemented")
}
