/*
 * Cloud API
 *
 * The public facing API through which connectors are exposed as a single abstract API
 *
 * API version: v1.5
 * Contact: support@trexis.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finite

// Transaction - Transaction object
type Transaction struct {

	// Unique identifier of the entity
	EntityId string `json:"entityId,omitempty"`

	// Unique identifier of the account in the system of record
	AccountId string `json:"accountId,omitempty"`

	// Unique identifier of the transaction in the system of record
	Id string `json:"id,omitempty"`

	// An integer sequence that can be used for ordering transactions within one day.
	SequenceInDay int32 `json:"sequenceInDay,omitempty"`

	Status TransactionStatus `json:"status,omitempty"`

	// The amount of the transaction when it was executed and booked to the account.
	ExecutedAmount float32 `json:"executedAmount,omitempty"`

	// The currency code of the executed amount
	ExecutedCurrencyCode string `json:"executedCurrencyCode,omitempty"`

	// The exchange rate used to convert the originating amount to the executing amount
	ExchangeRate float32 `json:"exchangeRate,omitempty"`

	// The originating amount of the transaction when it was originally submitted to the account.
	OriginatingAmount float32 `json:"originatingAmount,omitempty"`

	// The currency code of the originating transaction amount
	OriginatingCurrencyCode string `json:"originatingCurrencyCode,omitempty"`

	Direction string `json:"direction,omitempty"`

	// The balance of the account at the moment this transaction was executed
	RunningBalance float32 `json:"runningBalance,omitempty"`

	// ISO 6801 date of when the transaction was created in the system of record
	CreatedDate string `json:"createdDate,omitempty"`

	// ISO 6801 date of when the transaction was posted to the account
	PostedDate string `json:"postedDate,omitempty"`

	// ISO 6801 date of when the transaction was executed and booked to the account
	ExecutedDate string `json:"executedDate,omitempty"`

	// ISO 6801 date of when the transaction was updated on the account
	UpdatedDate string `json:"updatedDate,omitempty"`

	// Unique identifier of the transaction in the system of record
	Description string `json:"description,omitempty"`

	// Additional information about the transaction
	Memo string `json:"memo,omitempty"`

	// The grouping of this transaction in the system of record
	Group string `json:"group,omitempty"`

	// The type of this transaction in the system of record
	Type string `json:"type,omitempty"`

	// The main category of the transaction
	MainCategory string `json:"mainCategory,omitempty"`

	// The sub category of the transaction
	SubCategory string `json:"subCategory,omitempty"`

	// The check number associated with the transaction in case it was a check
	CheckNumber string `json:"checkNumber,omitempty"`

	Images BinaryItemList `json:"images,omitempty"`

	// The latitude coordinate where the transaction took place
	Latitude string `json:"latitude,omitempty"`

	// The longitude coordinate where the transaction took place
	Longitude string `json:"longitude,omitempty"`

	// The code used to identify the merchant for the transaction
	MerchantCode string `json:"merchantCode,omitempty"`

	// true if this transaction is a reversal, false otherwise.
	Reversal bool `json:"reversal,omitempty"`

	// The transaction identifier this transaction is reversing
	ReversalFor string `json:"reversalFor,omitempty"`

	// true if this transaction has been reversed, false otherwise.
	Reversed bool `json:"reversed,omitempty"`

	// The transaction identifier this transaction was reversed by
	ReversedBy string `json:"reversedBy,omitempty"`

	Transactor Transactor `json:"transactor,omitempty"`

	URI FiniteUri `json:"URI,omitempty"`
}
