/*
 * Cloud API
 *
 * The public facing API through which connectors are exposed as a single abstract API
 *
 * API version: v1.5.1
 * Contact: support@trexis.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finite

// Address - Address object
type Address struct {
	Type string `json:"type,omitempty"`

	// Address line
	Line1 string `json:"line1,omitempty"`

	// Address line
	Line2 string `json:"line2,omitempty"`

	// Address line
	Line3 string `json:"line3,omitempty"`

	// Address City or Town
	City string `json:"city,omitempty"`

	// State or Region
	State string `json:"state,omitempty"`

	// Postal code or Zip code
	PostalCode string `json:"postalCode,omitempty"`

	// Country
	Country string `json:"country,omitempty"`

	// Primary Address
	Primary bool `json:"primary,omitempty"`
}
