/*
 * Cloud API
 *
 * The public facing API through which connectors are exposed as a single abstract API
 *
 * API version: v1.5
 * Contact: support@trexis.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finite

// BinaryItem - Binary Item Object
type BinaryItem struct {

	// The mime type of the binary content.
	Format string `json:"format,omitempty"`

	// The length of the binary content in bytes.
	Length int32 `json:"length,omitempty"`

	// List of attributes for a binary item, e.g description, creation time...
	Attributes []Attribute `json:"attributes,omitempty"`

	// A base64 encoded identifier used by the connectors to locate the binary item
	ItemId string `json:"itemId,omitempty"`

	// The optionally inlined base64 encoded content of the item.
	Content string `json:"content,omitempty"`

	URI FiniteUri `json:"URI,omitempty"`
}
