/*
 * Cloud API
 *
 * The public facing API through which connectors are exposed as a single abstract API
 *
 * API version: v1.5.1
 * Contact: support@trexis.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finite

// SecurityInformation - Security Information
type SecurityInformation struct {

	// Unique username
	Username string `json:"username,omitempty"`

	// Unique token to identify entity for subsequent requests.  E.g. OAuth access_token
	Token string `json:"token,omitempty"`

	// ISO 8601 date the entity last logged in
	LastLoginDate string `json:"lastLoginDate,omitempty"`
}
