// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/robinhuiser/finite-mock-server/ent/entityaddress"
	"github.com/robinhuiser/finite-mock-server/ent/predicate"
)

// EntityAddressQuery is the builder for querying EntityAddress entities.
type EntityAddressQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.EntityAddress
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntityAddressQuery builder.
func (eaq *EntityAddressQuery) Where(ps ...predicate.EntityAddress) *EntityAddressQuery {
	eaq.predicates = append(eaq.predicates, ps...)
	return eaq
}

// Limit adds a limit step to the query.
func (eaq *EntityAddressQuery) Limit(limit int) *EntityAddressQuery {
	eaq.limit = &limit
	return eaq
}

// Offset adds an offset step to the query.
func (eaq *EntityAddressQuery) Offset(offset int) *EntityAddressQuery {
	eaq.offset = &offset
	return eaq
}

// Order adds an order step to the query.
func (eaq *EntityAddressQuery) Order(o ...OrderFunc) *EntityAddressQuery {
	eaq.order = append(eaq.order, o...)
	return eaq
}

// First returns the first EntityAddress entity from the query.
// Returns a *NotFoundError when no EntityAddress was found.
func (eaq *EntityAddressQuery) First(ctx context.Context) (*EntityAddress, error) {
	nodes, err := eaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entityaddress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eaq *EntityAddressQuery) FirstX(ctx context.Context) *EntityAddress {
	node, err := eaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntityAddress ID from the query.
// Returns a *NotFoundError when no EntityAddress ID was found.
func (eaq *EntityAddressQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entityaddress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eaq *EntityAddressQuery) FirstIDX(ctx context.Context) int {
	id, err := eaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntityAddress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one EntityAddress entity is not found.
// Returns a *NotFoundError when no EntityAddress entities are found.
func (eaq *EntityAddressQuery) Only(ctx context.Context) (*EntityAddress, error) {
	nodes, err := eaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entityaddress.Label}
	default:
		return nil, &NotSingularError{entityaddress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eaq *EntityAddressQuery) OnlyX(ctx context.Context) *EntityAddress {
	node, err := eaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntityAddress ID in the query.
// Returns a *NotSingularError when exactly one EntityAddress ID is not found.
// Returns a *NotFoundError when no entities are found.
func (eaq *EntityAddressQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = &NotSingularError{entityaddress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eaq *EntityAddressQuery) OnlyIDX(ctx context.Context) int {
	id, err := eaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntityAddresses.
func (eaq *EntityAddressQuery) All(ctx context.Context) ([]*EntityAddress, error) {
	if err := eaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return eaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (eaq *EntityAddressQuery) AllX(ctx context.Context) []*EntityAddress {
	nodes, err := eaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntityAddress IDs.
func (eaq *EntityAddressQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := eaq.Select(entityaddress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eaq *EntityAddressQuery) IDsX(ctx context.Context) []int {
	ids, err := eaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eaq *EntityAddressQuery) Count(ctx context.Context) (int, error) {
	if err := eaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return eaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (eaq *EntityAddressQuery) CountX(ctx context.Context) int {
	count, err := eaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eaq *EntityAddressQuery) Exist(ctx context.Context) (bool, error) {
	if err := eaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return eaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (eaq *EntityAddressQuery) ExistX(ctx context.Context) bool {
	exist, err := eaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntityAddressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eaq *EntityAddressQuery) Clone() *EntityAddressQuery {
	if eaq == nil {
		return nil
	}
	return &EntityAddressQuery{
		config:     eaq.config,
		limit:      eaq.limit,
		offset:     eaq.offset,
		order:      append([]OrderFunc{}, eaq.order...),
		predicates: append([]predicate.EntityAddress{}, eaq.predicates...),
		// clone intermediate query.
		sql:  eaq.sql.Clone(),
		path: eaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntityAddress.Query().
//		GroupBy(entityaddress.FieldCountry).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (eaq *EntityAddressQuery) GroupBy(field string, fields ...string) *EntityAddressGroupBy {
	group := &EntityAddressGroupBy{config: eaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return eaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//	}
//
//	client.EntityAddress.Query().
//		Select(entityaddress.FieldCountry).
//		Scan(ctx, &v)
//
func (eaq *EntityAddressQuery) Select(field string, fields ...string) *EntityAddressSelect {
	eaq.fields = append([]string{field}, fields...)
	return &EntityAddressSelect{EntityAddressQuery: eaq}
}

func (eaq *EntityAddressQuery) prepareQuery(ctx context.Context) error {
	for _, f := range eaq.fields {
		if !entityaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eaq.path != nil {
		prev, err := eaq.path(ctx)
		if err != nil {
			return err
		}
		eaq.sql = prev
	}
	return nil
}

func (eaq *EntityAddressQuery) sqlAll(ctx context.Context) ([]*EntityAddress, error) {
	var (
		nodes   = []*EntityAddress{}
		withFKs = eaq.withFKs
		_spec   = eaq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, entityaddress.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &EntityAddress{config: eaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, eaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (eaq *EntityAddressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eaq.querySpec()
	return sqlgraph.CountNodes(ctx, eaq.driver, _spec)
}

func (eaq *EntityAddressQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := eaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (eaq *EntityAddressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entityaddress.Table,
			Columns: entityaddress.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entityaddress.FieldID,
			},
		},
		From:   eaq.sql,
		Unique: true,
	}
	if fields := eaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entityaddress.FieldID)
		for i := range fields {
			if fields[i] != entityaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, entityaddress.ValidColumn)
			}
		}
	}
	return _spec
}

func (eaq *EntityAddressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eaq.driver.Dialect())
	t1 := builder.Table(entityaddress.Table)
	selector := builder.Select(t1.Columns(entityaddress.Columns...)...).From(t1)
	if eaq.sql != nil {
		selector = eaq.sql
		selector.Select(selector.Columns(entityaddress.Columns...)...)
	}
	for _, p := range eaq.predicates {
		p(selector)
	}
	for _, p := range eaq.order {
		p(selector, entityaddress.ValidColumn)
	}
	if offset := eaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntityAddressGroupBy is the group-by builder for EntityAddress entities.
type EntityAddressGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eagb *EntityAddressGroupBy) Aggregate(fns ...AggregateFunc) *EntityAddressGroupBy {
	eagb.fns = append(eagb.fns, fns...)
	return eagb
}

// Scan applies the group-by query and scans the result into the given value.
func (eagb *EntityAddressGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := eagb.path(ctx)
	if err != nil {
		return err
	}
	eagb.sql = query
	return eagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := eagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EntityAddressGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) StringsX(ctx context.Context) []string {
	v, err := eagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = eagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) StringX(ctx context.Context) string {
	v, err := eagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EntityAddressGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) IntsX(ctx context.Context) []int {
	v, err := eagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = eagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) IntX(ctx context.Context) int {
	v, err := eagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EntityAddressGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := eagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = eagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) Float64X(ctx context.Context) float64 {
	v, err := eagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EntityAddressGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := eagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EntityAddressGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = eagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (eagb *EntityAddressGroupBy) BoolX(ctx context.Context) bool {
	v, err := eagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (eagb *EntityAddressGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range eagb.fields {
		if !entityaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := eagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (eagb *EntityAddressGroupBy) sqlQuery() *sql.Selector {
	selector := eagb.sql
	columns := make([]string, 0, len(eagb.fields)+len(eagb.fns))
	columns = append(columns, eagb.fields...)
	for _, fn := range eagb.fns {
		columns = append(columns, fn(selector, entityaddress.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(eagb.fields...)
}

// EntityAddressSelect is the builder for selecting fields of EntityAddress entities.
type EntityAddressSelect struct {
	*EntityAddressQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (eas *EntityAddressSelect) Scan(ctx context.Context, v interface{}) error {
	if err := eas.prepareQuery(ctx); err != nil {
		return err
	}
	eas.sql = eas.EntityAddressQuery.sqlQuery(ctx)
	return eas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (eas *EntityAddressSelect) ScanX(ctx context.Context, v interface{}) {
	if err := eas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) Strings(ctx context.Context) ([]string, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EntityAddressSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (eas *EntityAddressSelect) StringsX(ctx context.Context) []string {
	v, err := eas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = eas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (eas *EntityAddressSelect) StringX(ctx context.Context) string {
	v, err := eas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) Ints(ctx context.Context) ([]int, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EntityAddressSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (eas *EntityAddressSelect) IntsX(ctx context.Context) []int {
	v, err := eas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = eas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (eas *EntityAddressSelect) IntX(ctx context.Context) int {
	v, err := eas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EntityAddressSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (eas *EntityAddressSelect) Float64sX(ctx context.Context) []float64 {
	v, err := eas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = eas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (eas *EntityAddressSelect) Float64X(ctx context.Context) float64 {
	v, err := eas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EntityAddressSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (eas *EntityAddressSelect) BoolsX(ctx context.Context) []bool {
	v, err := eas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (eas *EntityAddressSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = eas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entityaddress.Label}
	default:
		err = fmt.Errorf("ent: EntityAddressSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (eas *EntityAddressSelect) BoolX(ctx context.Context) bool {
	v, err := eas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (eas *EntityAddressSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := eas.sqlQuery().Query()
	if err := eas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (eas *EntityAddressSelect) sqlQuery() sql.Querier {
	selector := eas.sql
	selector.Select(selector.Columns(eas.fields...)...)
	return selector
}
