// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/robinhuiser/fca-emu/ent/predicate"
	"github.com/robinhuiser/fca-emu/ent/routingnumber"
)

// RoutingNumberQuery is the builder for querying RoutingNumber entities.
type RoutingNumberQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.RoutingNumber
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoutingNumberQuery builder.
func (rnq *RoutingNumberQuery) Where(ps ...predicate.RoutingNumber) *RoutingNumberQuery {
	rnq.predicates = append(rnq.predicates, ps...)
	return rnq
}

// Limit adds a limit step to the query.
func (rnq *RoutingNumberQuery) Limit(limit int) *RoutingNumberQuery {
	rnq.limit = &limit
	return rnq
}

// Offset adds an offset step to the query.
func (rnq *RoutingNumberQuery) Offset(offset int) *RoutingNumberQuery {
	rnq.offset = &offset
	return rnq
}

// Order adds an order step to the query.
func (rnq *RoutingNumberQuery) Order(o ...OrderFunc) *RoutingNumberQuery {
	rnq.order = append(rnq.order, o...)
	return rnq
}

// First returns the first RoutingNumber entity from the query.
// Returns a *NotFoundError when no RoutingNumber was found.
func (rnq *RoutingNumberQuery) First(ctx context.Context) (*RoutingNumber, error) {
	nodes, err := rnq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{routingnumber.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rnq *RoutingNumberQuery) FirstX(ctx context.Context) *RoutingNumber {
	node, err := rnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoutingNumber ID from the query.
// Returns a *NotFoundError when no RoutingNumber ID was found.
func (rnq *RoutingNumberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rnq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{routingnumber.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rnq *RoutingNumberQuery) FirstIDX(ctx context.Context) int {
	id, err := rnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoutingNumber entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one RoutingNumber entity is not found.
// Returns a *NotFoundError when no RoutingNumber entities are found.
func (rnq *RoutingNumberQuery) Only(ctx context.Context) (*RoutingNumber, error) {
	nodes, err := rnq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{routingnumber.Label}
	default:
		return nil, &NotSingularError{routingnumber.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rnq *RoutingNumberQuery) OnlyX(ctx context.Context) *RoutingNumber {
	node, err := rnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoutingNumber ID in the query.
// Returns a *NotSingularError when exactly one RoutingNumber ID is not found.
// Returns a *NotFoundError when no entities are found.
func (rnq *RoutingNumberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rnq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = &NotSingularError{routingnumber.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rnq *RoutingNumberQuery) OnlyIDX(ctx context.Context) int {
	id, err := rnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoutingNumbers.
func (rnq *RoutingNumberQuery) All(ctx context.Context) ([]*RoutingNumber, error) {
	if err := rnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rnq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rnq *RoutingNumberQuery) AllX(ctx context.Context) []*RoutingNumber {
	nodes, err := rnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoutingNumber IDs.
func (rnq *RoutingNumberQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := rnq.Select(routingnumber.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rnq *RoutingNumberQuery) IDsX(ctx context.Context) []int {
	ids, err := rnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rnq *RoutingNumberQuery) Count(ctx context.Context) (int, error) {
	if err := rnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rnq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rnq *RoutingNumberQuery) CountX(ctx context.Context) int {
	count, err := rnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rnq *RoutingNumberQuery) Exist(ctx context.Context) (bool, error) {
	if err := rnq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rnq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rnq *RoutingNumberQuery) ExistX(ctx context.Context) bool {
	exist, err := rnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoutingNumberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rnq *RoutingNumberQuery) Clone() *RoutingNumberQuery {
	if rnq == nil {
		return nil
	}
	return &RoutingNumberQuery{
		config:     rnq.config,
		limit:      rnq.limit,
		offset:     rnq.offset,
		order:      append([]OrderFunc{}, rnq.order...),
		predicates: append([]predicate.RoutingNumber{}, rnq.predicates...),
		// clone intermediate query.
		sql:  rnq.sql.Clone(),
		path: rnq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Number string `json:"number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoutingNumber.Query().
//		GroupBy(routingnumber.FieldNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rnq *RoutingNumberQuery) GroupBy(field string, fields ...string) *RoutingNumberGroupBy {
	group := &RoutingNumberGroupBy{config: rnq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rnq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rnq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Number string `json:"number,omitempty"`
//	}
//
//	client.RoutingNumber.Query().
//		Select(routingnumber.FieldNumber).
//		Scan(ctx, &v)
//
func (rnq *RoutingNumberQuery) Select(field string, fields ...string) *RoutingNumberSelect {
	rnq.fields = append([]string{field}, fields...)
	return &RoutingNumberSelect{RoutingNumberQuery: rnq}
}

func (rnq *RoutingNumberQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rnq.fields {
		if !routingnumber.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rnq.path != nil {
		prev, err := rnq.path(ctx)
		if err != nil {
			return err
		}
		rnq.sql = prev
	}
	return nil
}

func (rnq *RoutingNumberQuery) sqlAll(ctx context.Context) ([]*RoutingNumber, error) {
	var (
		nodes = []*RoutingNumber{}
		_spec = rnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &RoutingNumber{config: rnq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, rnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rnq *RoutingNumberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rnq.querySpec()
	return sqlgraph.CountNodes(ctx, rnq.driver, _spec)
}

func (rnq *RoutingNumberQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rnq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rnq *RoutingNumberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   routingnumber.Table,
			Columns: routingnumber.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: routingnumber.FieldID,
			},
		},
		From:   rnq.sql,
		Unique: true,
	}
	if fields := rnq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routingnumber.FieldID)
		for i := range fields {
			if fields[i] != routingnumber.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rnq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rnq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, routingnumber.ValidColumn)
			}
		}
	}
	return _spec
}

func (rnq *RoutingNumberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rnq.driver.Dialect())
	t1 := builder.Table(routingnumber.Table)
	selector := builder.Select(t1.Columns(routingnumber.Columns...)...).From(t1)
	if rnq.sql != nil {
		selector = rnq.sql
		selector.Select(selector.Columns(routingnumber.Columns...)...)
	}
	for _, p := range rnq.predicates {
		p(selector)
	}
	for _, p := range rnq.order {
		p(selector, routingnumber.ValidColumn)
	}
	if offset := rnq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rnq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoutingNumberGroupBy is the group-by builder for RoutingNumber entities.
type RoutingNumberGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rngb *RoutingNumberGroupBy) Aggregate(fns ...AggregateFunc) *RoutingNumberGroupBy {
	rngb.fns = append(rngb.fns, fns...)
	return rngb
}

// Scan applies the group-by query and scans the result into the given value.
func (rngb *RoutingNumberGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rngb.path(ctx)
	if err != nil {
		return err
	}
	rngb.sql = query
	return rngb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rngb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rngb.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) StringsX(ctx context.Context) []string {
	v, err := rngb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rngb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) StringX(ctx context.Context) string {
	v, err := rngb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rngb.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) IntsX(ctx context.Context) []int {
	v, err := rngb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rngb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) IntX(ctx context.Context) int {
	v, err := rngb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rngb.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rngb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rngb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rngb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rngb.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rngb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rngb *RoutingNumberGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rngb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rngb *RoutingNumberGroupBy) BoolX(ctx context.Context) bool {
	v, err := rngb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rngb *RoutingNumberGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rngb.fields {
		if !routingnumber.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rngb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rngb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rngb *RoutingNumberGroupBy) sqlQuery() *sql.Selector {
	selector := rngb.sql
	columns := make([]string, 0, len(rngb.fields)+len(rngb.fns))
	columns = append(columns, rngb.fields...)
	for _, fn := range rngb.fns {
		columns = append(columns, fn(selector, routingnumber.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(rngb.fields...)
}

// RoutingNumberSelect is the builder for selecting fields of RoutingNumber entities.
type RoutingNumberSelect struct {
	*RoutingNumberQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rns *RoutingNumberSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rns.prepareQuery(ctx); err != nil {
		return err
	}
	rns.sql = rns.RoutingNumberQuery.sqlQuery(ctx)
	return rns.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rns *RoutingNumberSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rns.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rns.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rns *RoutingNumberSelect) StringsX(ctx context.Context) []string {
	v, err := rns.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rns.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rns *RoutingNumberSelect) StringX(ctx context.Context) string {
	v, err := rns.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rns.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rns *RoutingNumberSelect) IntsX(ctx context.Context) []int {
	v, err := rns.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rns.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rns *RoutingNumberSelect) IntX(ctx context.Context) int {
	v, err := rns.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rns.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rns *RoutingNumberSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rns.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rns.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rns *RoutingNumberSelect) Float64X(ctx context.Context) float64 {
	v, err := rns.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rns.fields) > 1 {
		return nil, errors.New("ent: RoutingNumberSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rns *RoutingNumberSelect) BoolsX(ctx context.Context) []bool {
	v, err := rns.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (rns *RoutingNumberSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rns.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{routingnumber.Label}
	default:
		err = fmt.Errorf("ent: RoutingNumberSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rns *RoutingNumberSelect) BoolX(ctx context.Context) bool {
	v, err := rns.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rns *RoutingNumberSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rns.sqlQuery().Query()
	if err := rns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rns *RoutingNumberSelect) sqlQuery() sql.Querier {
	selector := rns.sql
	selector.Select(selector.Columns(rns.fields...)...)
	return selector
}
