// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/robinhuiser/finite-mock-server/ent/account"
	"github.com/robinhuiser/finite-mock-server/ent/branch"
	"github.com/robinhuiser/finite-mock-server/ent/entity"
	"github.com/robinhuiser/finite-mock-server/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	branchFields := schema.Branch{}.Fields()
	_ = branchFields
	// branchDescState is the schema descriptor for state field.
	branchDescState := branchFields[4].Descriptor()
	// branch.StateValidator is a validator for the "state" field. It is called by the builders before save.
	branch.StateValidator = branchDescState.Validators[0].(func(string) error)
	entityFields := schema.Entity{}.Fields()
	_ = entityFields
	// entityDescID is the schema descriptor for id field.
	entityDescID := entityFields[0].Descriptor()
	// entity.DefaultID holds the default value on creation for the id field.
	entity.DefaultID = entityDescID.Default.(func() uuid.UUID)
}
