/*
 * Cloud API
 *
 * The public facing API through which connectors are exposed as a single abtract API
 *
 * API version: v1.5
 * Contact: support@trexis.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FiniteUri - Unique Resource Identifier in the API
type FiniteUri struct {

	// The URL to the URI
	URL string `json:"URL,omitempty"`
}
